#!/bin/bash
#conda activate cmake # not needed here. Pero hace falta para instalar bien ggpubr antes de correr esto

## will run for inputs:
## - 0.8 0.5 0.1 0.05 0.01 0.008 0.005 0.001 0.25 0.05 0.04 0.025 0.005 0.004 0.0025 0.0005 0.0004 0.00025
## - size 10000 10e+06
## - uniform lognormal
## - sp in 10 100 1000
## - 30 samples for community type (-n 30)


## Simuls folder format::
## simul_folder => ../results_null_model/simcomms_2023-02-16/
## filenames    => "SIMCOMM_SIMS_0.8_uniform_10000_sp_10_9/simul_9_t_86.csv"
##                                 3       4     5     7 8           1

n=30 # number of unique samples for each community type

for fdil in 0.8 0.5 0.1 0.05 0.01 0.008 0.005 0.001 0.25 0.05 0.04 0.025 0.005 0.004 0.0025 0.0005 0.0004 0.00025
do
    for size in 10000 10e+06
    do
      for sp in 10 100 1000
      do
        for distrib in uniform lognormal
        do
          ## Choose number of groups
          if [ $sp -eq 10 ]
          then
            groupslist="2 3"
          elif [ $sp -eq 100 ]
          then
            groupslist="2 3 5 10 25"
          else # sp == 1000
            groupslist="2 3 5 10 25 50 100"
          fi
          
          for g in $groupslist
          do
            ## Choose group distribution
            if [ $distrib = "uniform" ]
            then
              pcgtable=../1_datasets/PCGtables/EvenGroups_N"$g"_"$sp"sp.csv
            else
              pcgtable=../1_datasets/PCGtables/SkewedGroups_N"$g"_"$sp"sp.csv
            fi
            
            ## PCGtable is chosen; run script.          
            echo "launching script for abundance table: ./test_data/SIMCOMM_SIMS_"$fdil"_"$distrib"_"$size"_sp_"$sp"(...)"
            echo "with PCG table: "$pcgtable
            Rscript create_data_simcomms.R --input ./test_data/SIMCOMM_SIMS_"$fdil"_"$distrib"_"$size"_sp_"$sp"_ -n "$n" -p "$pcgtable"
        done
      done
    done
  done
done
